### ISSUE TITLE
Py4JJavaError: An error occurred while calling o108.load. : org.elasticsearch.hadoop.EsHadoopIllegalArgumentException: Cannot find mapping for netflow-*/ - one is required before using Spark SQL

### ISSUE THREAD

**Issue by DAYceng** [coyiotis/ELK-SJ#1]
hi，I am a beginner in spark. 
I tried to deploy using ELKSJ, but I encountered a problem【My operating environment is a ubantu18.04 virtual machine (VMware)】
![image](https://user-images.githubusercontent.com/39471587/140631162-0ea4bb7c-e93e-4cdb-bd56-5b68321e81af.png)

`---------------------------------------------------------------------------
Py4JJavaError                             Traceback (most recent call last)
<ipython-input-6-35c649c9a608> in <module>
----> 1 flowDF = es_reader.load("netflow-*/")

/usr/local/spark/python/pyspark/sql/readwriter.py in load(self, path, format, schema, **options)
    164         self.options(**options)
    165         if isinstance(path, basestring):
--> 166             return self._df(self._jreader.load(path))
    167         elif path is not None:
    168             if type(path) != list:

/usr/local/spark/python/lib/py4j-0.10.7-src.zip/py4j/java_gateway.py in __call__(self, *args)
   1255         answer = self.gateway_client.send_command(command)
   1256         return_value = get_return_value(
-> 1257             answer, self.gateway_client, self.target_id, self.name)
   1258 
   1259         for temp_arg in temp_args:

/usr/local/spark/python/pyspark/sql/utils.py in deco(*a, **kw)
     61     def deco(*a, **kw):
     62         try:
---> 63             return f(*a, **kw)
     64         except py4j.protocol.Py4JJavaError as e:
     65             s = e.java_exception.toString()

/usr/local/spark/python/lib/py4j-0.10.7-src.zip/py4j/protocol.py in get_return_value(answer, gateway_client, target_id, name)
    326                 raise Py4JJavaError(
    327                     "An error occurred while calling {0}{1}{2}.\n".
--> 328                     format(target_id, ".", name), value)
    329             else:
    330                 raise Py4JError(

Py4JJavaError: An error occurred while calling o108.load.
: org.elasticsearch.hadoop.EsHadoopIllegalArgumentException: Cannot find mapping for netflow-*/ - one is required before using Spark SQL
	at org.elasticsearch.spark.sql.SchemaUtils$.discoverMappingAndGeoFields(SchemaUtils.scala:105)
	at org.elasticsearch.spark.sql.SchemaUtils$.discoverMapping(SchemaUtils.scala:91)
	at org.elasticsearch.spark.sql.ElasticsearchRelation.lazySchema$lzycompute(DefaultSource.scala:229)
	at org.elasticsearch.spark.sql.ElasticsearchRelation.lazySchema(DefaultSource.scala:229)
	at org.elasticsearch.spark.sql.ElasticsearchRelation$$anonfun$schema$1.apply(DefaultSource.scala:233)
	at org.elasticsearch.spark.sql.ElasticsearchRelation$$anonfun$schema$1.apply(DefaultSource.scala:233)
	at scala.Option.getOrElse(Option.scala:121)
	at org.elasticsearch.spark.sql.ElasticsearchRelation.schema(DefaultSource.scala:233)
	at org.apache.spark.sql.execution.datasources.DataSource.resolveRelation(DataSource.scala:403)
	at org.apache.spark.sql.DataFrameReader.loadV1Source(DataFrameReader.scala:223)
	at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:211)
	at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:178)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
	at py4j.Gateway.invoke(Gateway.java:282)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.GatewayConnection.run(GatewayConnection.java:238)
	at java.lang.Thread.run(Thread.java:748)`

This is an error that occurs when running the code in Jupiter
Seems to be the problem with this line of code：
`flowDF = es_reader.load("netflow-*/")`
It seems that something is not loaded

From the log, it seems that the data in elasticsearch is not found or the data format is wrong. But I am not sure if this is the problem, and after the mirror deployment is completed, I cannot access elasticsearch through port 9200, and I have no idea to solve it.
In addition, I have never found the deployment location of the netflow mirror
Has anyone encountered a similar problem?

**Comment by coyiotis** [comment]
Hi @DAYceng, you must first feed some netflow records to the collector, so that the pipeline pushed the data to an appropriate ES index. Then you can define the ES mapping for this particulart index using Kibana UI. 

After that everything should fall in place! Hope you will find the above useful :)

**Comment by DAYceng** [comment]
> Hi @DAYceng, you must first feed some netflow records to the collector, so that the pipeline pushed the data to an appropriate ES index. Then you can define the ES mapping for this particulart index using Kibana UI.
> 
> After that everything should fall in place! Hope you will find the above useful :)

thanks for your answer
